[tool.isort]
profile = "black"

[tool.flake8]
max-line-length = 88
exclude = [".venv", "__pycache__",]
# Ignore some of the most obnoxious linting errors.
ignore = [
    "W503", "E226",
    # Missing Docstrings
    "D100", "D104", "D105", "D106", "D107",
    # Docstring Whitespace
    "D203", "D212", "D214", "D215",
    # Docstring Quotes
    "D301", "D302",
    # Docstring Content
    "D400", "D401", "D402", "D404", "D405", "D406", "D407", "D408", "D409", "D410", "D411", "D412", "D413", "D414", "D416", "D417",
    # Comments
    "E266", "E203"
    # Whitespace
]
